PierreMarket/Controllers/FlavorsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using PierreMarket.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreMarket.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly PierreMarketContext _db;

    public FlavorsController(PierreMarketContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.OrderBy(x => x.FlavorName).ToList();
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      return View();
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Create(Flavor newObject)
    {
      _db.Flavors.Add(newObject);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Flavor model = _db.Flavors
      .Include(x => x.Treats)
      .ThenInclude(join => join.Treat)
      .FirstOrDefault(x => x.FlavorId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult AddTreat(int id)
    {
      Flavor model = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult AddTreat(Flavor objectGettingAdd, int TreatId)
    {
      if (TreatId != 0)
        {
          if(_db.FlavorTreat.Where(x => x.FlavorId == objectGettingAdd.FlavorId && x.TreatId == TreatId).ToHashSet().Count == 0)
          {
            _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = objectGettingAdd.FlavorId });
          }
        }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = objectGettingAdd.FlavorId});
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult DeleteTreat(int FlavorTreatId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == FlavorTreatId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      Flavor model = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Edit(Flavor edittedObject)
    {
      _db.Entry(edittedObject).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Delete(int id)
    {
      Flavor model = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor model = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      _db.Flavors.Remove(model);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

PierreMarket/Controllers/ManageUsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using PierreMarket.Models;
using Microsoft.EntityFrameworkCore;

namespace PierreMarket.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<ApplicationUser>
            _userManager;

        public ManageUsersController(
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var admins = (await _userManager
                .GetUsersInRoleAsync("Administrator"))
                .ToArray();

            var everyone = await _userManager.Users
                .ToArrayAsync();

            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };

            return View(model);
        }

    }
}

PierreMarket/Controllers/OrdersController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using PierreMarket.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreMarket.Controllers
{
  [Authorize]
  public class OrdersController : Controller
  {
    private readonly PierreMarketContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public OrdersController(UserManager<ApplicationUser> userManager, PierreMarketContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userOrders = _db.Orders.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userOrders);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Order newObject)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      newObject.User = currentUser;
      _db.Orders.Add(newObject);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Order model = _db.Orders
      .Include(x => x.Treats)
      .ThenInclude(x => x.Treat)
      .FirstOrDefault(x => x.OrderId == id);
      return View(model);
    }

    public ActionResult AddTreat(int id)
    {
      Order model = _db.Orders.FirstOrDefault(x => x.OrderId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(model);
    }

    [HttpPost]
    public ActionResult AddTreat(Order objectGettingAdd, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.OrderTreat.Add(new OrderTreat() { TreatId = TreatId, OrderId = objectGettingAdd.OrderId });
      }
      Order order = _db.Orders.FirstOrDefault(x => x.OrderId == objectGettingAdd.OrderId);
      Treat treat = _db.Treats.FirstOrDefault(x => x.TreatId == TreatId);
      order.OrderTotalCost += treat.TreatCost;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = objectGettingAdd.OrderId});
    }

    [HttpPost]
    public ActionResult DeleteTreat(int OrderTreatId)
    {
      OrderTreat joinEntry = _db.OrderTreat.FirstOrDefault(entry => entry.OrderTreatId == OrderTreatId);
      Order order = _db.Orders.FirstOrDefault(x => x.OrderId == joinEntry.OrderId);
      Treat treat = _db.Treats.FirstOrDefault(x => x.TreatId == joinEntry.TreatId);
      order.OrderTotalCost -= treat.TreatCost;
      _db.OrderTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Order model = _db.Orders.FirstOrDefault(x => x.OrderId == id);
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Order edittedObject)
    {
      _db.Entry(edittedObject).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Order model = _db.Orders.FirstOrDefault(x => x.OrderId == id);
      return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Order model = _db.Orders.FirstOrDefault(x => x.OrderId == id);
      _db.Orders.Remove(model);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

PierreMarket/Controllers/TreatsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using PierreMarket.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierreMarket.Controllers
{
  public class TreatsController : Controller
  {
    private readonly PierreMarketContext _db;

    public TreatsController(PierreMarketContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.OrderBy(x => x.TreatName).ToList();
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      return View();
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Treat model = _db.Treats
      .Include(x => x.Flavors)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(x => x.TreatId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult AddFlavor(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(x => x.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
        {
          if(_db.FlavorTreat.Where(x => x.FlavorId == FlavorId && x.TreatId == treat.TreatId).ToHashSet().Count == 0)
          {
            _db.FlavorTreat.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = FlavorId });
          }
        }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId});
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult DeleteFlavor(int FlavorTreatId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == FlavorTreatId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(x => x.TreatId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Edit(Treat edittedObject)
    {
      _db.Entry(edittedObject).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Delete(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(x => x.TreatId == id);
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(x => x.TreatId == id);
      _db.Treats.Remove(model);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

PierreMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Pierre's Market</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-fallback-test-class="sr-only"
asp-fallback-test-property="position" asp-fallback-test-value="absolute" crossorigin="anonymous"
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/styles.css" type="text/css">
  </head>
  <body>
      @Html.Partial("_NavBar")
    <div class="container">
      @RenderBody()
    </div>
  </body>
</html>

PierreMarket/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
  <div class="container">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pierre's Market</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a href="/" class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a href="/Flavors" class="nav-link text-dark" asp-area="" asp-controller="Flavors" asp-action="Index">Flavors</a>
        </li>
        <li class="nav-item">
          <a href="/Treats" class="nav-link text-dark" asp-area="" asp-controller="Treats" asp-action="Index">Treats</a>
        </li>
        <li class="nav-item">
          @if (User.Identity.IsAuthenticated)
          {
            <a href="/Orders" class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
          }
        </li>
        <li class="nav-item">
          @if (User.Identity.Name == "admin@pierremarket.local")
          {
            <a href="/ManageUsers" class="nav-link text-dark" asp-area="" asp-controller="ManageUsers" asp-action="Index">Manage Users</a>
          }
        </li>
      </ul>
    </div>
    <div class="logout">
            @using System.Security.Claims
            @if (User.Identity.IsAuthenticated)
            {
              @using (Html.BeginForm("LogOff", "Account"))
              {
                <p><input type="submit" value="Log out" class="btn btn-secondary btn-sm" /></p>
              }
            }
            else
            {
              <ul>
                @Html.ActionLink("Login", "Login", "Account", null, new { @class="btn btn-info btn-sm"})
                @Html.ActionLink("Register", "Register", "Account", null, new { @class="btn btn-info btn-sm"})
              </ul>
            }
          </div>
  </div>
</nav>